### ISSUE TITLE
Symphony component does not exists (finder/finder)

### ISSUE THREAD

**Issue by 3D-I** [phpbb-extensions/phpbb-ext-skeleton#10]
in skeleton/helper/packager the use of  'Symfony\Component\Finder\Finder' is declared and thus into the function 'create_zip($data)' it is called. But in phpBB 3.1.x that Symphony Folder does not exists hence this error:

 Class 'Symfony\Component\Finder\Finder' not found in \ext\phpbb\skeleton\helper\packager.php on line 167 ...

---> line: 		$finder = new Finder();

phpbb/finder.php should be used? Maybe a switch to be created for the 2 phpBB series?

$phpbb_extension_manager?

**Comment by VSEphpbb** [comment]
This is being addressed.

In the meantime you should use this ext inside a clone of the phpBB repo, instead of a packaged release. Because the development of phpBB does have Symphony/Finder.

**Comment by 3D-I** [comment]
I wasn't aware of this, thanks.
