### ISSUE TITLE
extension:create cli does not register, nor does the created console skeleton sample command

### ISSUE THREAD

**Issue by chrishecker** [phpbb-extensions/phpbb-ext-skeleton#133]
The extension:create CLI command does not register when this extension is installed and enabled.  The extension shows enabled in both the ACP and extension:show in the CLI, but no extension:create.  This is on phpbb 3.3.4, php 7.4.23.  If I take the sample skeleton and move it into the phpbb/console/command hierarchy and hack stuff up, I can get it to work, so the sample.php is fine, it's just the services.yml is not being read or something? 

I don't see any errors in the logs, even with DEBUG and DEBUG_EXTRA on.

I actually can't find a single example of a working extension with a CLI component for modern phpbb...I guess I'll hack my stuff into the main tree for now? 

Thanks,
Chris

**Comment by DavidIQ** [comment]
Adding cli commands to an extension should work just fine without having to hack anything up. This extension wouldn't have anything to do with that though. Please post in [Extension Writers Discussion](https://www.phpbb.com/community/viewforum.php?f=461) if you require further assistance in getting a cli command to work. I'll leave this open so we can later review what the Extension Skeleton might be missing from the generated code.

**Comment by chrishecker** [comment]
Ok, I will ask there.  I'm more than willing to believe this is my fault somehow, I just can't figure out how.  I installed the skeleton from both the docs release and github here (running composer after), both act identically, the extension works in the UI but doesn't show up in the command line.

Chris

**Comment by DavidIQ** [comment]
Oh wait...I misread this. Thought you were having a problem with the generated extension. You're having a problem with the skeleton extension responding to the `create` cli command?

**Comment by chrishecker** [comment]
Yeah, the extension:create does not show up at all.   Nor does the generated one, but yeah, the skeleton's CLI isn't in the list and you can't execute it, even though the extension works fine through the board UI.

Chris

**Comment by chrishecker** [comment]
This person was having the same issues but there are no followups so I don't know if they worked it out:  https://www.phpbb.com/customise/db/official_tool/ext_skeleton/support/topic/199076

I assume if you install the skeleton on a 3.3.4 phpbb installation you get the command extension:create in your CLI?

**Comment by 3D-I** [comment]
> 
> 
> Yeah, the extension:create does not show up at all. Nor does the generated one, but yeah, the skeleton's CLI isn't in the list and you can't execute it, even though the extension works fine through the board UI.
> 
> Chris

![image](https://user-images.githubusercontent.com/480857/134957130-fc46e20d-d88b-4b8f-88f3-4cb479358475.png)


![image](https://user-images.githubusercontent.com/480857/134957186-9ebb3eaf-972f-4deb-85cd-10d2735e440a.png)

**Comment by chrishecker** [comment]
Weird, I wonder what is busted about my install then...nothing shows up in logs or anywhere and everything but this seems to work fine...

Chris

**Comment by iMattPro** [comment]
Run the `list` command and see if it shows up. Also purge your cache `cache:purge` just in case.

This is in phpBB 3.3.4.

<img width="874" alt="Screen Shot 2021-09-27 at 10 33 54 AM" src="https://user-images.githubusercontent.com/303711/134957715-482840e6-3f48-46d0-81da-a7ce54f3fcb7.png">

**Comment by chrishecker** [comment]
I've run list a bunch, but I'll try cache:purge now...

**Comment by iMattPro** [comment]
Are you seeing it in the nav bar of your forum?

**Comment by chrishecker** [comment]
Yeah, it works fine in the forum, I even generated a console skeleton with it (that also didn't register its command).  

cache:purge made no difference, sadly.

Chris

**Comment by chrishecker** [comment]
Just diffed my enter live phpbb tree from vanilla 3.3.4 and there are basically no diffs (files in mine, obvs, config.php, a couple super minor edits I made to add quoting replies to PMs).  Hrm.

**Comment by DavidIQ** [comment]
I've seen this problem before, but have never found a solution. Can you share your php.ini settings, if possible? Also what environment are you in?

**Comment by chrishecker** [comment]
CentOS 7 latest, nothing odd in php.ini except I have the memory/post/upload sizes set to 1000M, I have acpu installed and running with 128M shm size but it's not remotely full or fragmented right now, xdebug is installed but disabled.  I mean, I can send you the actual files I think, doesn't look like there's anything private in there.

**Comment by iMattPro** [comment]
Try [this extension](https://www.phpbb.com/customise/db/extension/database_optimize_and_repair_tool) just to see if its CLI commands appear:

**Comment by chrishecker** [comment]
> Try [this extension](https://www.phpbb.com/customise/db/extension/database_optimize_and_repair_tool) just to see if its CLI commands appear

Hmm, nope.  Okay, so clearly something is wonky with my install somehow.

I even just tried running composer update and that changed nothing (a bunch of packages updated that I'm going to revert now).

I've tried moving the services.yml around a bit to no avail, where this stuff gets loaded is so indirected it's hard to even think about trying to debug it.

**Comment by iMattPro** [comment]
So it's probably not an extension issue, but either a phpBB issue, or server OS issue?

**Comment by chrishecker** [comment]
Yeah, that DB extension was helpful, thanks, I couldn't find any in the repo here that had console commands.

I'm not sure where to go from here, especially if DavidIQ has seen it before and hasn't been able to solve it.  I feel like I would need to figure out where to put some log statements or something so I can figure out where/why it's not reading the services.yml that adds the console command (if that's indeed what's happening, or not happening).

**Comment by 3D-I** [comment]
> 
> 
> Yeah, that DB extension was helpful, thanks, I couldn't find any in the repo here that had console commands.
> 
Can you try https://www.phpbb.com/customise/db/extension/nore/ ?

**Comment by gRegorLove** [comment]
> Edit: here is a similar issue with cron tasks not being found when generated by the skeleton: https://tracker.phpbb.com/browse/PHPBB3-16591

:wave: That's me. I'm still experiencing that so subscribing to follow the conversation. Let me know if there's anything I can provide, like specific php.ini values.

**Comment by chrishecker** [comment]
Not me…is there some weird way it’s persistent somehow?  I’m not at my pc
so I can’t experiment right now, but I’m definitely not passing that parm
manually.

**Comment by gRegorLove** [comment]
Me neither. I'm running `php74 ./bin/phpbbcli.php cron:list -vvv`

**Comment by chrishecker** [comment]
cache:purge should also probably print something besides "[OK] Cache successfully purged." if it can't, like, actually purge the cache?

**Comment by gRegorLove** [comment]
@chrishecker Interesting! This could quite possibly be it. I don't have root access on this server, but SuEXEC is not running, so the cache files are indeed written by Apache's `nobody`, triggered by normal browsing of the forum. The `container_*` files in /cache/production are 0644 and the `data_*` are 0755.

I usually have been purging cache from the web admin, but I tried the CLI `cache:purge` and found it didn't clear/cache/production. That makes sense -- the CLI is running as our account, not `nobody`. There was no output from the command, like you noted, even with the very-verbose flag.

**Comment by 3D-I** [comment]
So are we saying that any CLI command should check the permissions of your user or group in the filesystem and produce an error message if something doesn't work?

**Comment by chrishecker** [comment]
I haven’t thought about the exact fix but it seems like at a minimum if the
library that parses all the services and tries to write the php and meta
files fails to do so and it doesn’t work right if it fails to do so, it
should at least log the error.

**Comment by chrishecker** [comment]
And cache:purge should definitely not give the happy green OK!  :)

**Comment by 3D-I** [comment]
So the problem shifts exclusively to the bug-tracker and as far as the response factor is concerned when the operation on the filesystem is actually completed. nothing apparently relates or correlates to this extension. It seems pretty clear to me that we should open another ticket about this and keep the objective factors and issues separate and distinct. Or am I missing something?

**Comment by 3D-I** [comment]
So the problem shifts exclusively to the bug-tracker and as far as the response factor is concerned when the operation on the filesystem is actually completed. nothing apparently relates or correlates to this extension. It seems pretty clear to me that we should open another ticket about this and keep the objective factors and issues separate and distinct. Or am I missing something?

**Comment by chrishecker** [comment]
Yes, it’s not specific to this extension and should be a phpbb bug…the
existing cron ticket linked above could be morphed into it since that
appears to be the same bug.  I assume this thread will not get deleted?  It
was weird not seeing any issues here, I’m not a GitHub person though so
maybe that’s normal for closed issues, I assume they’re findable somehow.

**Comment by 3D-I** [comment]
Also if closed the issue still exists and it is linkable.

**Comment by gRegorLove** [comment]
Agreed re: bug tracker. I'm not sure best practices whether my ticket should be modified or a new one created. I'll defer to those with more experience.

**Comment by iMattPro** [comment]
See https://tracker.phpbb.com/browse/PHPBB3-16591
