### ISSUE TITLE
Add more extension parts to the skeleton

### ISSUE THREAD

**Issue by rxu** [phpbb-extensions/phpbb-ext-skeleton#18]
The "roadmap" for adding more elements to the skeleton extension for completeness:
- [x] Cron
- [x] Console command
- [x] Notification
- [x] UCP/MCP modules
- [ ] ACP template event listener
- [x] ext.php
- [x] Build script

**Comment by 3D-I** [comment]
Some folder for separated functions maybe? 
Like functions, core, etc..

**Comment by VSEphpbb** [comment]
No, empty folders is just bloat.

We should also add the ext.php file as an option.

**Comment by 3D-I** [comment]
Agreed.

- ACP template events .. @rxu care to expand please?

**Comment by VSEphpbb** [comment]
He's talking about a template event for the adm/style folder.

**Comment by 3D-I** [comment]
I see. Thanks.

I'd go for a mandatory ext.php instead, not enough checks are done by phpBB itself at this time and all the Feature requests about adding those have been delayed to 3.3.
Just a thought.

**Comment by rxu** [comment]
Actuaally you can have ACP template events in your extension too, but Matt is correct about what did I mean :smiley: Fixed the description.

**Comment by VSEphpbb** [comment]
No on the mandatory ext.php. That file is not required, and should not be used at all if it's empty of code.

If ext authors want to use that file, they have the option to have one generated in their skeleton, which they can use for whatever purposes they have.

**Comment by 3D-I** [comment]
Agreed.

Good job VSE, testing first release.
I would like to add something here:

- controllers for ACP and if the case also for UCP/MCP.

Thaks for the great job, Matt.

**Comment by VSEphpbb** [comment]
I'm not actually into the ACP template listener idea because we already have template events in the main style, and in the ADM, it's the exact same thing...except the ADM section is a whole separate component, part of the ACP module, so it doesn't make a whole lot of sense to me to try sticking that into the skeleton as well.
