### ISSUE TITLE
composer.json needs updating

### ISSUE THREAD

**Issue by 3D-I** [phpbb-extensions/phpbb-ext-skeleton#19]
https://github.com/phpbb-extensions/phpbb-ext-skeleton/blame/3.1.x/composer.json#L15-L24

Considering the fact that at least one PR is devoted to make this 3.2 compatible the **composer.json** should take into consideration that for 3.2 the minimup PHP required is 5.4.

Also for completeness the **<3.2.0@dev** bit should be removed.

About the EPV an issue has been already created.

**Comment by VSEphpbb** [comment]
The minimum PHP version is an option the user enters themselves. It's up to them to decide what they want/need it to be.
