### ISSUE TITLE
The parameter "core.cache_dir" must be defined.

### ISSUE THREAD

**Issue by RMcGirr83** [phpbb-extensions/phpbb-ext-skeleton#20]
Installed on a 3.2 test forum and got this error.

**Comment by VSEphpbb** [comment]
Can you be more specific/detailed, I have not seen that. Thanks. Where, when, how'd you get it

**Comment by rxu** [comment]
You get it after hitting submit button.

![32_skeleton_err](https://cloud.githubusercontent.com/assets/212322/14253924/bdc02b08-fab7-11e5-92f2-5a1945584fae.jpg)

**Comment by VSEphpbb** [comment]
Fixed
