### ISSUE TITLE
Extension Skeleton 1.0.0-alpha1

### ISSUE THREAD

**Issue by RMcGirr83** [phpbb-extensions/phpbb-ext-skeleton#27]
Release has an empty phpbb file, or whatever, with a size of 0 when extracted?

**Comment by VSEphpbb** [comment]
Not sure what you mean by that. It's all fine here.

**Comment by RMcGirr83** [comment]
Not sure myself, extracted the file and I don't see it so maybe it's a winrar thing

![untitled](https://cloud.githubusercontent.com/assets/179079/14360654/705da40c-fcc5-11e5-84b3-e55b1769eec0.png)

**Comment by VSEphpbb** [comment]
I do not see that:
![screen shot 2016-04-07 at 10 43 18 am](https://cloud.githubusercontent.com/assets/303711/14360988/af67dd1a-fcad-11e5-9297-d57a1ee46981.png)

**Comment by RMcGirr83** [comment]
Odd

On Thu, Apr 7, 2016 at 1:44 PM, Matt Friedman <notifications@github.com>
wrote:

> I do not see that:
> [image: screen shot 2016-04-07 at 10 43 18 am]
> <https://cloud.githubusercontent.com/assets/303711/14360988/af67dd1a-fcad-11e5-9297-d57a1ee46981.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/phpbb-extensions/phpbb-ext-skeleton/issues/27#issuecomment-207022014>
>



-- 
Rich McGirr

**Comment by marc1706** [comment]
Can't reproduce that on Windows 10 with the latest WinRAR version.

**Comment by RMcGirr83** [comment]
Using Windows 7 and it's a work computer.  :shrug: I wouldn't worry about
it.  Go ahead and close the issue Matt.

On Thu, Apr 7, 2016 at 2:22 PM, Marc Alexander <notifications@github.com>
wrote:

> Can't reproduce that on Windows 10 with the latest WinRAR version.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/phpbb-extensions/phpbb-ext-skeleton/issues/27#issuecomment-207036595>
>



-- 
Rich McGirr

**Comment by VSEphpbb** [comment]
I tried it on a Windows 7 VM, so... Just download another copy I guess.
