### ISSUE TITLE
Not required Migration files created.

### ISSUE THREAD

**Issue by 3D-I** [phpbb-extensions/phpbb-ext-skeleton#39]
Once the _User control panel (UCP)_ and _Moderator control panel (MCP)_ are un-checked the logic still creates those migration files.

To add, there is not a check-box for _create schema_, but the logic does create that migration file too.

Database migration should be better defined I guess.
Thx.

**Comment by rxu** [comment]
Couldn't reproduce the issue with the latest code.

**Comment by 3D-I** [comment]
I am using this
https://github.com/phpbb-extensions/phpbb-ext-skeleton/releases/tag/1.0.0-b1
like a normal user

**Comment by 3D-I** [comment]
@rxu there are migrations files created while those shouldn't be..
I am not sure I explained the issue as it should have be, sorry.

**Comment by VSEphpbb** [comment]
When migrations are checked, all migrations are made. They're all samples, so when you choose migrations, you get all sample migrations available.
