### ISSUE TITLE
But the link remains always visible, also to guests

### ISSUE THREAD

**Issue by stealthForex** [phpbb-extensions/phpbb-ext-skeleton#46]
Am I wrong or the link to "Create skeleton extension" in the navbar remains always visible, also to guests?

I think very strange that a guest that visit my site, can create his own extensions....

Thanks, Marco

**Comment by VSEphpbb** [comment]
This is a developer tool. It's not intended to be used on live production sites, as it serves no purpose whatsoever to forum users.
