### ISSUE TITLE
unable to delete store/ext-tmp/extname

### ISSUE THREAD

**Issue by 3D-I** [phpbb-extensions/phpbb-ext-skeleton#61]
Say you created an extension named "myawesomeextension" with some components but you aren't satisfied of the resulting package due to some cause, it doesn't really matter.. now you want to recreate it with the same name.

Here's a screenshot of the error (deleting from the store folder the old extension will do but..)
![store_update_ext_1](https://cloud.githubusercontent.com/assets/480857/21375593/e82ddbf8-c72e-11e6-8dbb-d4735a3dfa68.png)

**Comment by VSEphpbb** [comment]
I've never had this problem. Check your folder permissions?

**Comment by 3D-I** [comment]
Windows 7 with EasyPHP. ?¿
