### ISSUE TITLE
Bug with 3.1.12 --> "finder"

### ISSUE THREAD

**Issue by 3D-I** [phpbb-extensions/phpbb-ext-skeleton#75]
Using the present repo with phpBb 3.1.12 (no probs with 3.2.2)

![skel3112](https://user-images.githubusercontent.com/480857/37630068-b17d5290-2be2-11e8-9d13-fc0adda3341e.png)

**Comment by DavidIQ** [comment]
Not sure we would do anything about this since 3.1 has reached EoL.
